"""Bridges gitignored local files onto a Colab VM without transiting GitHub.

Rationale (for the reviewer): `skills_pack/` and `public-test.jsonl` are
gitignored on purpose and must never be committed or pushed — the dataset
content in them must not transit GitHub at all, public or private. But the
Colab notebook that actually runs benchmarks is driven by colab-mcp, which
can only *add code cells* to the notebook (there's no file-upload RPC in
that bridge). So the only channel left is: encode the file as text, paste it
into one or more code cells, and have Colab-side code decode and reassemble
it. That's what this script automates in two steps:

    pack       local file -> gzip -> base64 -> split into N numbered .txt
               chunks + a manifest (sha256 of the original, chunk count,
               target filename) — run this on the dev machine.
    emit-cells manifest -> ready-to-paste Python source, one cell per few
               chunks, that reassembles the chunks, gunzips, verifies the
               sha256, and writes the file at /content/skills_pack/<name>
               — paste this into colab-mcp `add_code_cell` calls and run
               them in order on the Colab side.

Each emitted cell is kept under ~90KB of source text so it fits comfortably
under typical Jupyter/Colab per-cell size limits; --chunk-bytes controls how
much base64 payload goes in per data line, and how many chunks are grouped
per emitted cell is derived from that so the two knobs can't drift apart.

Usage:
    python scripts/colab_file_transfer.py pack skills_pack/selected_questions.jsonl \\
        --outdir /tmp/skills_pack_chunks
    python scripts/colab_file_transfer.py emit-cells /tmp/skills_pack_chunks/manifest.json \\
        > /tmp/cells.txt
    # then paste each printed cell (separated by "# ---- CELL N ----") into
    # colab-mcp add_code_cell, in order, and run each one.

This script itself contains no dataset content — it operates on whatever
file path is given at the command line.
"""

import argparse
import base64
import gzip
import hashlib
import json
import math
from pathlib import Path

DEFAULT_CHUNK_BYTES = 40_000
# Each cell holds this many chunk-lines before we cut a new one; kept small
# enough that CHUNKS_PER_CELL * (chunk-bytes-as-base64-line + quoting
# overhead) stays under ~90KB of Python source.
MAX_CELL_SOURCE_BYTES = 90_000


# --------------------------------------------------------------------------
# pack
# --------------------------------------------------------------------------

def cmd_pack(args) -> None:
    src = Path(args.file)
    if not src.is_file():
        raise SystemExit(f"ERROR: no such file: {src}")

    raw = src.read_bytes()
    sha256 = hashlib.sha256(raw).hexdigest()
    compressed = gzip.compress(raw, compresslevel=9)
    encoded = base64.b64encode(compressed).decode("ascii")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    chunk_bytes = args.chunk_bytes
    n_chunks = math.ceil(len(encoded) / chunk_bytes) or 1

    for i in range(n_chunks):
        piece = encoded[i * chunk_bytes : (i + 1) * chunk_bytes]
        (outdir / f"chunk_{i:04d}.txt").write_text(piece, encoding="ascii")

    manifest = {
        "target_filename": src.name,
        "orig_size_bytes": len(raw),
        "compressed_b64_size_bytes": len(encoded),
        "sha256": sha256,
        "n_chunks": n_chunks,
        "chunk_bytes": chunk_bytes,
        "chunk_files": [f"chunk_{i:04d}.txt" for i in range(n_chunks)],
    }
    manifest_path = outdir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(f"packed {src} ({len(raw)} bytes) -> {n_chunks} chunk(s) in {outdir}")
    print(f"sha256={sha256}")
    print(f"manifest -> {manifest_path}")


# --------------------------------------------------------------------------
# emit-cells
# --------------------------------------------------------------------------

REASSEMBLE_HEADER = '''\
# ---- CELL {cell_idx} of {n_cells}: skills-pack file transfer ({filename}) ----
# Chunks {first}-{last} of {n_chunks} for target "{target_filename}"
# (Generated by scripts/colab_file_transfer.py emit-cells — do not hand-edit.)
import base64, gzip, hashlib, os

_TRANSFER_STATE = globals().setdefault("_SKILLS_PACK_TRANSFER", {{}})
_slot = _TRANSFER_STATE.setdefault({slot_key!r}, {{"parts": {{}}, "manifest": {manifest_json}}})
_parts = _slot["parts"]
'''

REASSEMBLE_FOOTER = '''
_manifest = _slot["manifest"]
if len(_parts) == _manifest["n_chunks"]:
    _encoded = "".join(_parts[i] for i in range(_manifest["n_chunks"]))
    _compressed = base64.b64decode(_encoded)
    _raw = gzip.decompress(_compressed)
    _got_sha = hashlib.sha256(_raw).hexdigest()
    assert _got_sha == _manifest["sha256"], (
        f"sha256 mismatch: got {_got_sha}, expected {_manifest['sha256']}"
    )
    _outdir = "/content/skills_pack"
    os.makedirs(_outdir, exist_ok=True)
    _outpath = os.path.join(_outdir, _manifest["target_filename"])
    with open(_outpath, "wb") as _f:
        _f.write(_raw)
    print(f"OK: wrote {_outpath} ({len(_raw)} bytes), sha256 verified")
else:
    print(f"received {len(_parts)}/{_manifest['n_chunks']} chunks so far, "
          "waiting for remaining cells")
'''


def _chunks_per_cell(chunk_bytes: int) -> int:
    # Rough per-line source overhead for `_parts[i] = "..."` plus quoting;
    # stay well under MAX_CELL_SOURCE_BYTES even for the largest chunk size.
    per_line_overhead = 40
    per_cell_budget = MAX_CELL_SOURCE_BYTES - 2000  # headroom for header/footer text
    n = max(1, per_cell_budget // (chunk_bytes + per_line_overhead))
    return n


def cmd_emit_cells(args) -> None:
    manifest_path = Path(args.manifest)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    chunk_dir = manifest_path.parent

    n_chunks = manifest["n_chunks"]
    chunk_bytes = manifest["chunk_bytes"]
    per_cell = _chunks_per_cell(chunk_bytes)
    n_cells = math.ceil(n_chunks / per_cell)
    slot_key = manifest["sha256"][:12]

    manifest_json = json.dumps(manifest)

    for cell_idx in range(n_cells):
        lo = cell_idx * per_cell
        hi = min(lo + per_cell, n_chunks)
        body_lines = [
            REASSEMBLE_HEADER.format(
                cell_idx=cell_idx + 1,
                n_cells=n_cells,
                filename=manifest["target_filename"],
                first=lo,
                last=hi - 1,
                n_chunks=n_chunks,
                target_filename=manifest["target_filename"],
                slot_key=slot_key,
                manifest_json=manifest_json,
            )
        ]
        for i in range(lo, hi):
            chunk_file = chunk_dir / manifest["chunk_files"][i]
            piece = chunk_file.read_text(encoding="ascii")
            body_lines.append(f"_parts[{i}] = {piece!r}")
        if cell_idx == n_cells - 1:
            body_lines.append(REASSEMBLE_FOOTER)
        else:
            body_lines.append(
                f'\nprint(f"received {{len(_parts)}}/{n_chunks} chunks so far")'
            )
        cell_source = "\n".join(body_lines)

        if len(cell_source.encode("utf-8")) > MAX_CELL_SOURCE_BYTES:
            print(
                f"WARNING: cell {cell_idx + 1} is "
                f"{len(cell_source.encode('utf-8'))} bytes, over the "
                f"{MAX_CELL_SOURCE_BYTES}-byte target — reduce --chunk-bytes at pack time",
                file=__import__("sys").stderr,
            )

        print(cell_source)
        print(f"\n# ---- END CELL {cell_idx + 1} ----\n")


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    pack_ap = sub.add_parser("pack", help="gzip+base64 a file into numbered chunk files + a manifest")
    pack_ap.add_argument("file", help="local file to pack (any type; gitignored files are fine — this never touches git)")
    pack_ap.add_argument("--chunk-bytes", type=int, default=DEFAULT_CHUNK_BYTES, help="base64 bytes per chunk file")
    pack_ap.add_argument("--outdir", required=True, help="directory to write chunk_*.txt + manifest.json")

    emit_ap = sub.add_parser("emit-cells", help="print ready-to-paste Colab cell source that reassembles the packed file")
    emit_ap.add_argument("manifest", help="path to manifest.json produced by `pack`")

    args = ap.parse_args()
    if args.cmd == "pack":
        cmd_pack(args)
    elif args.cmd == "emit-cells":
        cmd_emit_cells(args)


if __name__ == "__main__":
    main()
